name: Build and deploy .NET Core app to Windows WebApp apinhousefeed
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: apinhousefeed
  AZURE_WEBAPP_PACKAGE_PATH: templates/NuGetFeedTemplate/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.apinhousefeed_c7eb }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: templates/NuGetFeedTemplate
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Add NuGet Feed
      shell: pwsh
      run: |
        dotnet nuget add source ${{ secrets.IN_HOUSE_NUGET_FEED }} -u ${{ secrets.IN_HOUSE_NUGET_USER }} -p ${{ secrets.IN_HOUSE_API_KEY }} -n InHouse --store-password-in-clear-text
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
