name: Build Templates

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual Run'

jobs:

  build:
    name: Build & Pack Template
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Pack Templates
        run: ./pack.ps1 -Version 1.0.$($env:GITHUB_RUN_NUMBER)

      - name: NuGet Packages
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: Artifacts/

      - name: NuGet Publish
        if: ${{ github.event.workflow_run.event != 'pull_request' }}
        uses: dansiegel/publish-nuget@v1.01
        with:
          feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
          apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

      # - name: NuGet Publish
      #   if: ${{ github.event.workflow_run.event != 'pull_request' }}
      #   uses: dansiegel/publish-nuget@v1.01
      #   with:
      #     apiKey: ${{ secrets.NUGET_API_KEY }}