name: Build Templates

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build & Pack Template
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Pack Templates
        run: ./pack.ps1 -Version 1.0.$($env:GITHUB_RUN_NUMBER)

      - name: NuGet Packages
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Artifacts/

  # publish:
    
  #   name: Publish NuGet Package
  #   runs-on: windows-latest
  #   env:
  #     DOTNET_CLI_TELEMETRY_OPTOUT: 1

  #   steps:
  #     - name: Download NuGet Template
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: NuGet

      - name: NuGet Publish
        if: ${{ github.event.workflow_run.event != 'pull_request' }}
        uses: myci-actions/publish-nuget@2
        with:
          filename: '*.nupkg'
          repo-url: ${{ secrets.IN_HOUSE_NUGET_FEED }}
          api-key: ${{ secrets.IN_HOUSE_API_KEY }}

      - name: NuGet Publish
        if: ${{ github.event.workflow_run.event != 'pull_request' }}
        uses: myci-actions/publish-nuget@2
        with:
          filename: '*.nupkg'
          api-key: ${{ secrets.NUGET_API_KEY }}